config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  
  resources :users do
    resources :apps do
      resources :versions
    end
  end
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  "
  get '/', to: 'users#index'
  get '/new', to: 'users#new'
  post '/new', to: 'users#create'
  
  get '/:username', to: 'users#show'
  get '/:username/new', to: 'apps#new'
  post '/:username', to: 'apps#create'
  
  get '/:username/:appname', to: 'apps#show'
  get '/:username/:appname/new', to: 'versions#new'
  post '/:username/:appname', to: 'versions#create'
  
  get '/:username/:appname/:version', to: 'versions#show'
  "
  #get '/:username/edit', to: 'users#edit'
  
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :user
  has_many :versions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :apps
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :app
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_user, only: [:show, :new, :edit, :create, :update, :destroy]
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @versions = @app.versions
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = @user.apps.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to user_app_path(@user, @app), notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
  
    def set_app
      @app = @user.apps.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:title, :package)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @apps = @user.apps
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_user, only: [:show, :new, :edit, :create, :update, :destroy]
  before_action :set_app, only: [:show, :new, :edit, :create, :update, :destroy]
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = @app.versions.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to user_app_version_path(@user, @app, @version), notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to user_app_path(@user, @app), notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
  
    def set_app
      @app = @user.apps.find(params[:app_id])
    end
  
    def set_version
      @version = @app.versions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:name, :code, :download, :description, :app_id, :force, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/apps/_form.html.erb
<%= form_for(app, url: {action: "create"}) do |f| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :package %>
    <%= f.text_field :package %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.title %></td>
        <td><%= app.user %></td>
        <td><%= link_to 'Show', user_app_path(@user, app) %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', '/' + @user.username %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @app.title %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Download</th>
      <th>Description</th>
      <th>Status</th>
      <th>Force</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.name %></td>
        <td><%= version.code %></td>
        <td><%= version.download %></td>
        <td><%= version.description %></td>
        <td><%= version.status %></td>
        <td><%= version.force %></td>
        <td><%= link_to 'Show', user_app_version_path(@user, @app, version) %></td>
        <td><!--<%= link_to 'Edit', edit_user_app_version_path(@user, @app, version) %>--></td>
        <td><%= link_to 'Destroy', user_app_version_path(@user, @app, version), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_user_app_version_path(@user, @app) %> | 

<!--<%= link_to 'Edit', edit_user_app_path(@user, @app) %> |-->
<%= link_to 'Back', user_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AChangeLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><!--<%= link_to 'Edit', '/' + user.username + '/edit' %>--></td>
        <td><!--<%= link_to 'Destroy', '/' + user.username, method: :delete, data: { confirm: 'Are you sure?' } %>--></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', '/' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<!--<%= link_to 'Edit', '/' + @user.username + '/edit' %> |-->

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.title %></td>
        <td><%= link_to 'Show', user_app_path(@user, app) %></td>
        <td><!--<%= link_to 'Edit', edit_user_app_path(@user, app) %>--></td>
        <td><!--<%= link_to 'Destroy', user_app_path(@user, app), method: :delete, data: { confirm: 'Are you sure?' } %>--></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_user_app_path(@user)  %> | <%= link_to 'Back', users_path %>

app/views/versions/_form.html.erb
<%= form_for(version, url: {action: "create"}) do |f| %>
  <% if version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :download %>
    <%= f.text_field :download %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.check_box :force %>
    <%= f.label :force %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_area :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Name</th>
      <th>Code</th>
      <th>Url</th>
      <th>Description</th>
      <th>App</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.version %></td>
        <td><%= version.name %></td>
        <td><%= version.code %></td>
        <td><%= version.url %></td>
        <td><%= version.description %></td>
        <td><%= version.app %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Back', user_app_path(@user, @app) %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @version.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @version.code %>
</p>

<p>
  <strong>Download:</strong>
  <%= @version.download %>
</p>

<p>
  <strong>Description:</strong>
  <%= @version.description %>
</p>

<p>
  <strong>Force:</strong>
  <%= @version.force %>
</p>

<p>
  <strong>Status:</strong>
  <%= @version.status %>
</p>

<!--<%= link_to 'Edit', edit_user_app_version_path(@user, @app, @version) %> |-->
<%= link_to 'Back', user_app_path(@user, @app) %>